### ISSUE TITLE
InMemoryBlogCache forever

### ISSUE THREAD

**Issue by dylanvdmerwe** [reactiveui/Akavache#164]
I'm using the latest prerelease of Akavache in Android and iPhone. However all the BlobCaches (LocalMachine, Secure, UserAccount) at run time are _always_ set to use InMemoryCache. 

I have all the caching that lives in it's own project which is where the nuget references live. I added a reference to Akavache.Sqlite3 in the main project to try and see if the cache would be persisted. On Android the Sqlite blob is used, however nothing seems to ever persist. InsertObject followed by GetObject returns null for a serialized and non-serialized object.

BlobCache.Secure.GetObject<T>(key).Subscribe(x => item = x, ex => { throw ex;});

On iPhone, I cannot get Sqlite3 to be used at all.

**Comment by c-lamont** [comment]
Still having this issue on 6.0.0-alpha0038

The linker was the issue and the solution above resolved it.

**Comment by Jyosua** [comment]
This also occurred for me on version 5.0.0 with a Xamarin.Forms project on .NET Standard 2.0
