### ISSUE TITLE
TryGet and/or Exists

### ISSUE THREAD

**Issue by prasannavl** [reactiveui/Akavache#186]
Add a mechanism for TryGet and/or Exists for high-performance scenarios. Current implementation throws an exception everytime incurring performance hit, everytime there is a cache miss. 

On the cards?

**Comment by allanchao** [comment]
Not to disagree with any of the discussion above, but I needed to check if a key exists without getting it. Just slightly modified the code above to the following. I called the method ContainsKey to match C# Dictionary but it's effectively an Exists(...)

`
        public static Task<bool> ContainsKey(this IBlobCache This, string key)
        {
            var tcs = new TaskCompletionSource<bool>();
            This.Get(key).Subscribe(
                x => tcs.SetResult(true),
                ex => tcs.SetResult(false));

            return tcs.Task;
        }
`

**Comment by glennawatson** [comment]
@allanchao feel free to make a new issue and submit a PR if you like.
