### ISSUE TITLE
Xamarin.iOS BlobCache.LocalMachine is null 

### ISSUE THREAD

**Issue by peteryongzhong** [reactiveui/Akavache#198]
```
BlobCache.LocalMachine.GetOrCreateObject (Variables.Post_keys, () => new Post_Data_Keys (), null).FirstOrDefaultAsync ().Wait ();
```

I was trying to use this code in a PCL project that is referenced by a Xamarin.iOS Unified project,
in AppDelegate's FinishedLaunching method I have set 

```
BlobCache.ApplicationName ="App";
```

and in the PCL project aswell.
However when I try to run this project a NullReferenceException will be thrown.

**Comment by dillorscroft** [comment]
How does this affect Xamarin Forms (v1.4.1.6349)  - Sorry I'm only a week or two into my Xamarin experience.

**Comment by tshtrifork** [comment]
Is there any update on this issue?

**Comment by jiujiu1123** [comment]
It works fine now with the new update, but I have to disable the Xamarin linker, I haven't looked into that issue though.

**Comment by martijn00** [comment]
I guess you have to add something to the linker like this: https://github.com/akavache/Akavache/blob/08b227fc81c84f0e056ef50d4aa548cf5cefb959/Akavache.Sqlite3/content/AkavacheSqliteLinkerOverride.cs.pp

**Comment by jiujiu1123** [comment]
I did, but it does not work for some reason, I guess I will try again tonight's

**Comment by Yortw** [comment]
I believe you have to add the preserve attribute to each (Akavache) class affected by the linker (with the allmembers property = true), or to each affected method (including constructors). Did you do that? I don't believe merely including the attribute definition and a static class decorated with it preserves everything (though I could be wrong and would love to know if I am). A better option, especially if Paul doesn't want the extra attribute sprinkled through his library is to configure your apps compiler options to specify the -linkskip argument for the Akavache assemblies. In that case the linker will ignore those assemblies but link others.

**Comment by paulcbetts** [comment]
@Yortw If you guys are seeing specific classes be taken by the linker, please report them so I can add them to the linker override!
