### ISSUE TITLE
SecureBlobCache hangs on inserts on WinRT

### ISSUE THREAD

**Issue by flagbug** [reactiveui/Akavache#205]
Using the latest version of Akavache, inserting an object into the `SecureBlobCache` sometimes just hangs. The normal BlobCache seems to work fine.

Here's a screenshot of the parallel stack, thank MS that I can't copy-paste it in text form :crying_cat_face: 

![2015-02-11 13 08 19](https://cloud.githubusercontent.com/assets/964691/6146618/138576d2-b1ef-11e4-9e97-86652108d9ec.png)

**Comment by dominik-weber** [comment]
1 1/2 years and still not a single comment? :(

**Comment by Bouncaaa** [comment]
Hello,

I am experiencing a similar problem except I can reproduce it systematically.
I am building a uwp for the surface pro and I am using MVVMLight.
I have a very simple login screen (2 fields and a button). The button calls an MVVMlight AsyncRelayCommand in which I first do an asynchronous call the the login web service and then I save the credentials into Blob.secure which hangs every time (through the extention method Blob.secure.SaveLogin(...)).

If I make a dummy call in the App.xaml.cs to Blob.secure.SaveLogin(...) then it all works fine.

Here is the login code:

```cs
ILoginRequest request = new LoginRequest(_apiKeychain.ClientId, userName, password);
ILoginResponse response = await _api.Login(request);
await _secureCache.SaveCredentials(userName, password);
await _secureCache.InsertObject(AccessTokenKey, response.Token);
return response.Token;
```

Note in the above code SaveCredentials is just a wrapper around Blob.secure.SaveLogin.

I just can't figure out why making dummy calls at startup changes anything.

Any help would be much appreciated.

Cheers

**Comment by Bouncaaa** [comment]
the solution proposed in #216 worked for me. Make a dummy call to the secure blob cache in the App.xaml.cs like await BlobCache.Secure.InsertObject("dummy", "dummy"); and this properly initializes Akavache.
