### ISSUE TITLE
JsonSerializerSettings not initalized for WinRT

### ISSUE THREAD

**Issue by gordonwatts** [reactiveui/Akavache#207]
I'm using Akavache (latest nuget version) in a Windows universal project. I cache a number of objects that are referenced by interfaces (e.g. IMeeting). To make this work correctly, I need the JsonSerializerSettings.TypeNameHandling set to all.

Looking in the source code, I see the Registrations.cs file, which contains exactly this, and it puts the JsonSerializerSettings object into Splat. However, in my code, when I use the locator to fetch an object of type JsonSerializerSettings, it returns null. It is as if the Registraion for this guy is not called.

The code is indirect enough I couldn't really determine under what circumstances (platforms, etc.) this was called. The driver code certainly looked like it would go looking for it. And there doesn't seem to be a pdb up on the net, so I couldn't really set into things to see what was happening.

Am I missing a init call? Or is this expected behavior on this platform? Many thanks!

**Comment by paulcbetts** [comment]
So, the trick to debugging is, build the library yourself, then drop the binaries in the packages folder over the shipped ones

**Comment by gordonwatts** [comment]
:-)

**Comment by paulcbetts** [comment]
Wait, did you try just registering your own JsonSerializerSettings?

**Comment by gordonwatts** [comment]
Yes, that seems to work. I just copied the settings out of Register.cs. And that works. The question is: should the code in Register.cs have executed (and I not have had to do the registration myself)?

**Comment by paulcbetts** [comment]
@gordonwatts It should've, but in this case you wanted to do something custom so you would've had to register something anyways

**Comment by gordonwatts** [comment]
Actually, I don't want anything custom. I just needed it different from the uninitialized defaults. But the defaults that are in ReactiveUI's Register.cs are perfect (actually, I just copied code from there into my own project to get it to work).
