### ISSUE TITLE
UTC dates deserialize as Local when using BSON reader

### ISSUE THREAD

**Issue by martinsmyllie** [reactiveui/Akavache#212]
In `SqlitePersistentBlobCacheNext.cs`, the Deserialize method initializes the BSON reader as follows:

`var settings = Locator.Current.GetService<JsonSerializerSettings>() ?? new JsonSerializerSettings();`
`var serializer = JsonSerializer.Create(settings);`
`var reader = new BsonReader(new MemoryStream(data));`

To get a Date to de-serialize dates as UTC doesn't the BsonReader constructor that specifies a `DateTimeKind` need to be used?

I know this issue has been raised previously #53... but either I'm missing something or it is still present.

**Comment by paulcbetts** [comment]
We always serialize as local and deserialize as local too, if you want to take that date and send it to somebody, you need to include the timezone

**Comment by escamoteur** [comment]
There Should be an option to store Dates just as UTC, as People with Mobile Devices my move between Timezones.

**Comment by poimis** [comment]
Is this still the case? I would claim that dates should ALWAYS be stored as UTC.

**Comment by kjeremy** [comment]
I'm seeing odd behavior where my `DateTimeOffset` objects are being stored as UTC and read back in local time on Android.

**Comment by PieterIddink** [comment]
The current version still has issues with storing date times. Now because local times seem to be stored without a UTC offset people will definitely have issues when changing their timezone settings on the device. I second the comment from @poimis: dates should ALWAYS be stored as UTC.

**Comment by glennawatson** [comment]
There is this setting https://github.com/reactiveui/Akavache/blob/19a24c757ef50e9219a28ca873e07a586e6fe3e3/src/Akavache.Core/BlobCache/IBlobCache.cs#L42

**Comment by PieterIddink** [comment]
Thanks for the quick reply. However, the method states:
>  Thus, DateTimes are serialized as UTC but deserialized as local time. 

But dates, by default,  are returned in DateTimeKind.Utc: 
[https://github.com/reactiveui/Akavache/blob/e18024c39e774b21d513d5bfc5eaa7bb0150c445/src/Akavache.Core/Json/JsonDateTimeTickConverter.cs#L55](url)

Shouldn't these be converted to DateTimeKind.Local?

**Comment by glennawatson** [comment]
We now serialkze and deserialize in UTC by default. Closing
