### ISSUE TITLE
Migrate to .net core 2.0

### ISSUE THREAD

**Issue by Zaid-Al-Omari** [reactiveui/Akavache#374]
When I import the package in an application which targets netcoreapp2.0 it will give a big yallow warning, because of packages like akavache.sqllite3 is being restored using .net framework 4.6.1

Is there any plans to get this to work in netcoreapp2.0 ?

**Comment by PureWeen** [comment]
There's a netstandard build that's currently in alpha that should work

https://www.myget.org/F/Akavache/api/v3/index.json
https://www.myget.org/F/akavache/api/v2

Have you tried that one yet?

**Comment by roggan87** [comment]
@PureWeen, I'm trying 6.0.0-alpha right now without success. I'm having a .net standard library depending on Akavache, that I've tried to test with NUnit or directly from a .net core console app on Win 10. Each time I'm getting:

> Message: System.TypeInitializationException : The type initializer for 'Akavache.BlobCache' threw an exception.
>
>  ----> System.Exception : Failed to initialize Akavache properly. Do you have a reference to Akavache.dll?

Splat won't catch the NUnit test runner on Windows, but I've explicitly told it, [like this](https://github.com/akavache/Akavache/issues/180#issuecomment-55924094), that I'm running through a test runner, still without success.

When referencing the .net standard library from an xamarin.android project it works just fine though.

The complete stack trace looks like this:

```
StackTrace:	at Akavache.BlobCache.get_LocalMachine()
   at Akavache.InMemoryBlobCache.OverrideGlobals(IScheduler scheduler, KeyValuePair`2[] initialContents)
   at hs.Tests.LocalCacheTests.<ValidRefreshToken_SuccessfullySaved>d__0.MoveNext() in \\hs.Tests\LocalCacheTests.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
--Exception
   at Akavache.Sqlite3.Registrations.Register(IMutableDependencyResolver resolver)
   at Akavache.DependencyResolverMixin.InitializeAkavache(IMutableDependencyResolver This)
   at Splat.Locator.RegisterResolverCallbackChanged(Action callback)
   at Akavache.BlobCache..cctor()
Result Message:	System.TypeInitializationException : The type initializer for 'Akavache.BlobCache' threw an exception.
  ----> System.Exception : Failed to initialize Akavache properly. Do you have a reference to Akavache.dll?
```

Any idea what I'm getting wrong?

**Comment by PureWeen** [comment]
Yea I see the same error as you with the current nuget alpha release..

I have a pull request out there for support with netcoreapp2.0
https://github.com/akavache/Akavache/pull/375

I tested it locally and it seems to work fine with a netcoreapp2.0 console app

I tried to do a netcoreapp1.1 target but it looks like that will take some extra work.    Will netcoreapp2.0 be alright? Or is netcoreapp1.1 pretty important ?

**Comment by roggan87** [comment]
Sweet! I'll try it out when I get a chance. netcoreapp2.0 is fine with me :)

**Comment by EmilAlipiev** [comment]
still not working and looks like not merged :(
