### ISSUE TITLE
Timeline for 6.X release?

### ISSUE THREAD

**Issue by aventurella** [reactiveui/Akavache#390]
Specifically looking for when this will be released: #377 
`fix: restrict system.reactive to 3.1.1 as min `

Or basically does it need to have `ReactiveUI` as a dependency vs `System.Reactive @ 3.1.1`?

**Comment by mesta1** [comment]
Is this project still alive ?

**Comment by melwil** [comment]
I'm wondering the same thing. I'm considering how to solve my storage needs for a new app, and this project keeps popping up in searches, but if it is not being maintained, we can't go for this.

**Comment by mesta1** [comment]
You have to use the 6.0 alpha, that's the latest stable. @PureWeen is an active maintainer, but I don't know if  he has admin privileges.

**Comment by PureWeen** [comment]
I have no privileges only good intentions :-)

**Comment by CR4567** [comment]
hey,
I'm wondering the same.
But where can I find the 6.0 alpha?

**Comment by mesta1** [comment]
nuget, tick prerelease packages

**Comment by cfl777** [comment]
Sad to see this project seems to be dying out? Anything progress since the beginning of this year?

**Comment by EmilAlipiev** [comment]
it is already released. please update your issue
