### ISSUE TITLE
DateTime and DateTimeOffset not saving microseconds and lower.

### ISSUE THREAD

**Issue by protocos** [reactiveui/Akavache#396]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/Akavache . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

No

**What is the current behavior?**

When I store and retrieve a DateTime or a DateTimeOffset object, I expect it to store the microseconds all the way to 7 decimal places. Otherwise this causes issues in our production systems.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Here's a test method to demonstrate the point. If you put a breakpoint on the "Assert", you can seethe two timestamps are different.

```
        [TestMethod]
        public async Task Akavache_GetOrFetchAsync_ShouldBeEqualEveryTime()
        {
            //Arrange
            var key = "key";
            var timestamp = DateTime.Now;
            Func<Task<TestObject>> fetchFunction = () => Task.FromResult(new TestObject
            {
                Timestamp = timestamp
            });

            //Act
            var firstResult = await BlobCache.InMemory.GetOrFetchObject<TestObject>(key, fetchFunction);
            var secondResult = await BlobCache.InMemory.GetOrFetchObject<TestObject>(key, fetchFunction);

            //Assert
            Assert.AreEqual(firstResult.Timestamp, secondResult.Timestamp);
        }

        class TestObject
        {
            public DateTimeOffset Timestamp {
                get;
                set;
            }
        }
```

**What is the expected behavior?**

Both timestamp results should be exactly the same up to the microseconds (7 decimal places)

**What is the motivation / use case for changing the behavior?**

I need my data to be exact coming out of the cache or the live system.

**Which versions of Akavache, and which platform / OS are affected by this issue? Did this work in previous versions of Akavache? Please also test with the latest stable and snapshot (https://www.myget.org/feed/Akavache/package/nuget/Akavache) versions.**

Akavache: v5.0.0
Windows 10
C# Framework 4.5
I don't know if it worked in previous versions of Akavache. I've only noticed it for this rare bug we keep getting.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by softlion** [comment]
Duplicate #269
