### ISSUE TITLE
Unable to insert object into Blobcache due to System.Reactive.Core requiring version 2.2.5.0

### ISSUE THREAD

**Issue by dberroa** [reactiveui/Akavache#399]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/Akavache . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When I call the following line:

await BlobCache.UserAccount.InsertObject(Key, value);

I get:

The type 'Unit' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reactive.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.	

I am unable to install this version on nuget as it is not available and another plugin required version 3.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Make a new Xamarain forms project using the latest version of forms. I made the project 4 days ago.

**What is the expected behavior?**

To be able to insert an object.

**What is the motivation / use case for changing the behavior?**

**Which versions of Akavache, and which platform / OS are affected by this issue? Did this work in previous versions of Akavache? Please also test with the latest stable and snapshot (https://www.myget.org/feed/Akavache/package/nuget/Akavache) versions.**

All. I'm doing this is the .NET standard share code.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by dberroa** [comment]
I made a stackoverflow post as well:

https://stackoverflow.com/questions/47859724/akavache-unit-is-defined-in-an-assembly-not-referenced-system-reactive-core-ver

**Comment by EmilAlipiev** [comment]
Do you see this for all platforms?  I am seeing it only on uwp but Android seems working for me

**Comment by EmilAlipiev** [comment]
I am using version 6 beta now but I am seeing this exception on UWP. Not sure if that is related?

`
System.ArgumentNullException: Value cannot be null. at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) at System.Reactive.ExceptionHelpers.ThrowIfNotNull(Exception exception) at T System.Reactive.Subjects.AsyncSubject`1.GetResult() `
