### ISSUE TITLE
Xamarin Forms BlobCache.LocalMachine on iOS lost after time?

### ISSUE THREAD

**Issue by michelmoorlag** [reactiveui/Akavache#414]
**Do you want to request a *feature* or report a *bug*?**
This is definitely a bug report

**What is the current behavior?**

When I save any data in BlobCache.LocalMachine on iOS it gets lost after an unpredictable amount of time. It doesn't matter if I use InsertObject or GetAndFetchLatest. After some time that can range from minutes to hours I get a KeyNotFound exception while I didn't Invalidate the key. I am also skipping the AbsoluteExpiration parameter. The same code runs on Android without any problem.  The BlobCache.Secure and BlobCache.UserAccount don't seem to have this problem. I tried different versions, tried settings a long AbsoluteExpiration but nothing seems to work.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create a new XF project, add Akavache Nuget and in App.xaml.cs override the OnStart() method like this:

	    protected override async void OnStart()
	    {
                BlobCache.ApplicationName = "MyCacheTest";
                BlobCache.EnsureInitialized();
	        try
	        {
	            var test = await BlobCache.LocalMachine.GetObject<string>("testKey");

	        }
	        catch (KeyNotFoundException e)
	        {
	            //this should happen only the very first time but on iOS I get this often
	            await BlobCache.LocalMachine.InsertObject<string>("testKey", "This is a test");

	        }
	    }

2. Set a breakpoint in the beginning of the method

3. In the AppDelegate add this code :

        private void UnregisterManagers()
        {
            Akavache.BlobCache.Shutdown().Wait();  // this calls the shutdown code
            Akavache.BlobCache.LocalMachine = null; // clear out the static cached variables
            Akavache.BlobCache.Secure = null;
            Akavache.BlobCache.UserAccount = null;
            FieldInfo fi = typeof(Akavache.BlobCache).GetField("shutdownRequested", BindingFlags.Static | BindingFlags.NonPublic);
            fi.SetValue(null, false); // reset the private flag
            Splat.Locator.Current = new Splat.ModernDependencyResolver(); // create a new dependency resolver so akavache has to create new objects when the app is resurrected.
        }

        public override void DidEnterBackground(UIApplication application)
        {
            //Console.WriteLine("App entering background state.");
            UnregisterManagers();
            base.DidEnterBackground(application);
        }
        // not guaranteed that this will run
        public override void WillTerminate(UIApplication application)
        {           
            //Console.WriteLine("App is terminating.");
            UnregisterManagers();
            base.WillTerminate(application);
        }

4. Add a class AkavacheSqliteLinkerOverride.cs to the root of the project if not there with code:

```
using System;
using Akavache.Sqlite3;

// Note: This class file is *required* for iOS to work correctly, and is 
// also a good idea for Android if you enable "Link All Assemblies".
namespace YourAppProjectName.iOS
{
    [Preserve]
    public static class LinkerPreserve
    {
        static LinkerPreserve()
        {
            throw new Exception(typeof(SQLitePersistentBlobCache).FullName);
        }
    }


    public class PreserveAttribute : Attribute
    {
    }
}
```

5. Run the app on a real device (I did not test on simulator) and see the Keynotfound exception is raised.
6. Close the app with the home button and immediate start the app again. It will get the data from cache.
7. Close the app again and wait for a day.
8. Open the app and see that the keynotfound exception is raised agian. The information is somehow lost?

**What is the expected behavior?**

I would expect that information on BlobCache.LocalMachine isn't lost after time.

**What is the motivation / use case for changing the behavior?**

I observed this behavior and it seems a bug to me. My goal is to help to improve Akavache.

**Which versions of Akavache, and which platform / OS are affected by this issue? Did this work in previous versions of Akavache? Please also test with the latest stable and snapshot (https://www.myget.org/feed/Akavache/package/nuget/Akavache) versions.**

I have tested with Akavache 5.0.0 and 6.0.0-Alpha0038 and both seems to have this problem. I am using Xamarin Forms v3.1.0.583944 with Visual Studio 15.7.4 and all the latest packages. On Android it works fine, only on iOS devices this is a problem.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by BillHally** [comment]
From the README.md:

#### The magic

* **Xamarin.iOS** may remove data, stored in `BlobCache.LocalMachine`, to free up disk space (only if your app is not running). The locations `BlobCache.UserAccount` and `BlobCache.Secure` will be backed up to iCloud and iTunes. (https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1)

**Comment by michelmoorlag** [comment]
Oohhh, now I feel really stupid :( Typical RTFM. Thank you for enlightening me :)

**Comment by PureWeen** [comment]
@michelmoorlag  the other thing to just make sure of is that you have all the necessary linker files setup for iOS

https://github.com/reactiveui/Akavache#handling-xamarin-linker

That's another issue people have had is that the SqlLite cache is getting linked out. If you check the type on LocalMachine and it's of type *MemoryCache* that won't be resilient.

I realize from your description that's not what it sounds like but just want to make sure

**Comment by michelmoorlag** [comment]
@PureWeen Thank you for pointing me on this. Should I add it to my shared project only or to all Os specific projects too?

I have a LinkerPreserve in every project but is has slightly different code so I guess it has changed over time.
