### ISSUE TITLE
Change Rx Nuget Dependencies to the new System.Reactive.*

### ISSUE THREAD

**Issue by jstawski** [reactiveui/Akavache#415]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/Akavache . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Currently, [Akavache Core](https://www.nuget.org/packages/akavache.core/) has a dependency on Rx-* packages. Those packages are old and were replaced by System.Reactive.* ones. Other packages that depend on System.Reactive.* are adding these packages and it is generating an ambiguous compilation error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create a Xamarin project, add the latest Akavache package. Add System.Reactive, System.Reactive.Core, System.Reactive.Linq and add code that uses `InsertObject` 

**What is the expected behavior?**
It should compile

**What is the motivation / use case for changing the behavior?**
Stay up to date with the right dependencies

**Which versions of Akavache, and which platform / OS are affected by this issue? Did this work in previous versions of Akavache? Please also test with the latest stable and snapshot (https://www.myget.org/feed/Akavache/package/nuget/Akavache) versions.**
Xamarin, PCL, 5.0.0

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by PureWeen** [comment]
These are being updated in the next 6.0 release which is what the current master branch is up to

If you install the alpha build from nuget that one uses all the system.reactve.* libraries
https://www.nuget.org/packages/akavache.core/6.0.0-alpha0038

**Comment by jstawski** [comment]
What other changes are included in 6.x? Is it only the nuget changes?

**Comment by KevM** [comment]
I am having a similar problem but related the fact that even the pre-release nuget seems fixed on `System.Reactive` version 3. 

```Version conflict detected for System.Reactive. Reference the package directly from the project to resolve this issue. 
 My.Nuget -> ReactiveProperty 5.1.1 -> System.Reactive (>= 4.0.0) 
 My.Nuget -> akavache.core 6.0.0-alpha0038 -> System.Reactive (>= 3.1.1 && < 4.0.0).			0	
```
