### ISSUE TITLE
Akavacke pre-release nugets are dependent on (non .net standard) System.Reactive v3

### ISSUE THREAD

**Issue by KevM** [reactiveui/Akavache#416]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/Akavache . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Taking a dependency on akavache.core v6 `Install-Package akavache.core -Version 6.0.0-alpha0038`
does not work when you have dependencies needing .net standard versions of  `System.Reactive` **>=v4**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* Create a new project. 
* Add a dependency to `ReactiveProperty` v5.1.1
* Add a dependency to ` akavache.core` pre-release 6.0.0-alpha0038

```
Version conflict detected for System.Reactive. Reference the package directly from the project to resolve this issue. 
 AI.Mobile -> ReactiveProperty 5.1.1 -> System.Reactive (>= 4.0.0) 
 AI.Mobile -> akavache.core 6.0.0-alpha0038 -> System.Reactive (>= 3.1.1 && < 4.0.0).			0	
```

**What is the expected behavior?**

Because these are both .net standard projects they should be dependent on .net standard nugets.

**What is the motivation / use case for changing the behavior?**

The v6 release seems to be targeting .net standard.

**Which versions of Akavache, and which platform / OS are affected by this issue? Did this work in previous versions of Akavache? Please also test with the latest stable and snapshot (https://www.myget.org/feed/Akavache/package/nuget/Akavache) versions.**

pre-release 6.0.0-alpha0038

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

It seems the .csproj for Akavache  assemblies have a hard reference to v3 of `System.Reactive`

```xml
<PackageReference Include="System.Reactive" Version="[3.1.1,4)" />
```

**Comment by KevM** [comment]
I took a stab and updating the `System.Reactive` dependency and ran into a transitive problem with `ReactiveUI`

```
C:\Users\user\source\repos\Akavache\src\Akavache.Mobile\Akavache.Mobile.csproj : error NU1107: Version conflict detected for System.Reactive. Reference the package directly from the proje
ct to resolve this issue.
C:\Users\user\source\repos\Akavache\src\Akavache.Mobile\Akavache.Mobile.csproj : error NU1107:  akavache.mobile -> akavache.core -> System.Reactive (>= 4.0.0)
C:\Users\user\source\repos\Akavache\src\Akavache.Mobile\Akavache.Mobile.csproj : error NU1107:  akavache.mobile -> ReactiveUI 8.2.1 -> System.Reactive (>= 3.1.1 && < 4.0.0).

```

**Comment by KevM** [comment]
Upgraded ReactiveUI and a bunch of other dependencies and hit a new problem. 

```
AkavacheDriver.cs(10,35): error CS0012: The type 'Unit' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reactive.Core, Version=3.0.3000.0, Cu
lture=neutral, PublicKeyToken=94bc3704cddfc263'. [.\Akavache\src\Akavache.Mobile\Akavache.Mobile.csproj]
```

Here is my work so far. https://github.com/reactiveui/Akavache/compare/master...KevM:system-reactive-v4?expand=1

**Comment by PureWeen** [comment]
@KevM  can you try the new https://www.nuget.org/packages/akavache/6.0.17-beta see if that works better for you?

**Comment by EmilAlipiev** [comment]
I installed latest stable version but it returns also error for android

![image](https://user-images.githubusercontent.com/10422347/45430576-eb662880-b6a5-11e8-911f-b39fc4121256.png)

**Comment by jBijsterboschNL** [comment]
Is there still any work in progress on this issue?

**Comment by KevM** [comment]
FYI When using System.Reactive > 4.1 for Xamarin deployments I've needed to downgrade System.Threading.Tasks.Extensions.

By adding this to my iOS and Android mobile apps .csproj.
```
    <PackageReference Include="System.Threading.Tasks.Extensions">
      <Version>4.4.0</Version>
    </PackageReference>
```

**Comment by PureWeen** [comment]
> I've needed to downgrade System.Threading.Tasks.Extensions.
Yea :-/ 
https://github.com/dotnet/corefx/issues/31726
