### ISSUE TITLE
Build problem on UWP

### ISSUE THREAD

**Issue by mesta1** [reactiveui/Akavache#422]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When building on AppCenter or VSTS a UWP application with minumum version Windows 10 Fall Creators Update (10.0; build 16299) it times out. On local machine, freezes happen. This happens only when building with Store-> Create App Packages

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1) Create a new UWP blank application, 
2) Project Properties -> Set minimum version to Windows 10 Fall Creators Update (10.0; build 16299)
3) Install Nuget prerelease 6.0.17 beta (it happens also with older versions)
4) Right click project -> Store -> Create app packages  
5) Build is very slow and pc freezes happens
or
4) Publish on VSTS or AppCenter and build there. Build gets stopped after 30 minutes.

**What is the expected behavior?**

If I remove the NuGet, the empty application builds without any problem.

**What is the motivation / use case for changing the behavior?**

I would like to use continous integration with my app

**Which versions of Akavache, and which platform / OS are affected by this issue? Did this work in previous versions of Akavache? Please also test with the latest stable and snapshot (https://www.myget.org/feed/Akavache/package/nuget/Akavache) versions.**

UWP Release with minimum version set to Windows 10 Fall Creators Update (10.0; build 16299)
Akavache 6 NuGet both prereleases.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by EmilAlipiev** [comment]
Did you try the latest stable version?

**Comment by mesta1** [comment]
Had no problems with last version, closing.
