### ISSUE TITLE
Encryption broken at 6.X

### ISSUE THREAD

**Issue by erik-hooper** [reactiveui/Akavache#428]
Bug Found after upgrading to 6.x on a WPF implementation using 4.6.2+

Currently the encryption uses the default encryption which is implemented in a class called ProtectedData in ProtectedDataShim as it is it just returns to byte array aka nothing. It looks like during the .net standard upgrade this used to reference the Protected data API from Microsoft. But was replaced with the "default" implementation by mistake.  

Work around.
Implement  `IEncryptionProvider` with a added reference to `System.Security.Cryptography.ProtectedData`
 ```csharp
using System;
using System.Security.Cryptography;
using System.Reactive.Linq;
    public class MyEncryptionProvider : Akavache.IEncryptionProvider
    {
        public IObservable<byte[]> EncryptBlock(byte[] block)
        {
            return Observable.Return(ProtectedData.Protect(block, null, DataProtectionScope.CurrentUser));
        }
        public IObservable<byte[]> DecryptBlock(byte[] block)
        {
            return Observable.Return(ProtectedData.Unprotect(block, null, DataProtectionScope.CurrentUser));
        }
    }
/// elsewhere
Locator.CurrentMutable.Register(() => new MyEncryptionProvider(), typeof(IEncryptionProvider));
```
I believe The ProtectedData package supports most xamarin .netstandard and other framework versions.  The package should be updated to reference this package for supported versions.

**Comment by cfl777** [comment]
Does this fix resolve these issues as well? 

https://github.com/reactiveui/Akavache/issues/190
