### ISSUE TITLE
BlobCache.UserAccount where is the cache stored?

### ISSUE THREAD

**Issue by mc-evgeny** [reactiveui/Akavache#431]
We are using `BlobCache.UserAccount` in our `Xamarin.Forms` project.
On Android when the app is uninstalled the cache is deleted as well.
On iOS when the app is uninstalled the caches is still there.

I am wondering if that is the expected behaviour.
If so, is it possible to delete/reset the cache on iOS manually in a none programmatically way?
If the data is being stored on iTunes or iCloud there also should be an option to delete this data under iOS settings like the rest of the apps do, but this data seems to be completely hidden.

**Comment by EmilAlipiev** [comment]
I havent developed for IOS and i dont know how it works as default but as you can see in the description, it says below
BlobCache.UserAccount - User settings. Some systems backup this data to the cloud.

I guess this what it is happening. On Android is possible also but not as default, you need to setup Android backup options. regarding wiping off the data, maybe you should check IOS documentation. it can be related to ios itsefl

**Comment by glennawatson** [comment]
Answer provided by @EmilAlipiev closing
