### ISSUE TITLE
e_sqlite3 DllNotFoundException on Akavache v6.0.20 and beyond

### ISSUE THREAD

**Issue by kriewall** [reactiveui/Akavache#442]
#### Do you want to request a feature or report a bug? 
Report a bug.

#### What is the current behavior
When running a WPF application using .NET Framework 4.6.1 or better and Akavache 6.0.20 or better, the following `DllNotFoundException` is thrown when `BlobCache.User.Account.GetObject<string>("key")` is called:

  `Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

[Here](https://1drv.ms/f/s!AsvM6Pyke4A6hTS3U2PUnCqr3ldk) is a demo of the problem.  Run the app and the exception should be thrown immediately.

#### What is the expected behavior?
No exception should be thrown; all SQLite dependencies should be automatically copied to the appropriate location in output folder on build.  

#### What is the motivation / use case for changing the behavior?
Enable use of Akavache v6.

#### Which versions of Akavache and which platform/OS are affected by this issue?  Did this work in previous versions of Akavache? Please also test with the latest stable and development snapshot. 
This issue occurs on Windows 10 Enterprise. Versions 6.0.20 and beyond are affected.  (I did not test the prerelease versions of v6.)  Version 5.0.0 is not affected.  

#### Other information (e.g. stacktraces, related issues, suggestions how to fix)
I tried specifying RuntimeIdentifier in the .csproj as win10-x64 and win10-x86, but it doesn't seem to have any effect.  My output folder contains the SQLite-related DLLs below (in bin/debug/net461).  If there's some simple setting I'm missing in my .csproj, please let me know. 

![image](https://user-images.githubusercontent.com/38048622/49468624-3a5dbe80-f7ba-11e8-877e-446bfc842024.png)

**Comment by PureWeen** [comment]
Hmmm :-/

If I move this code into the activated event on the window then I don't get the exception but the Cache call never resolves.

I tested with a console app and same thing there so something seems quirky with net45 targets

**Comment by PureWeen** [comment]
@kriewall   it looks like the sqlite bundle doesn't work fully work transitively

Can you try installing
 <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="1.1.11" />

into your head WPF project and then let me know if that works?

**Comment by kriewall** [comment]
@PureWeen Seems to work! Thanks!

**Comment by PureWeen** [comment]
@ericsink is this something that needs to be fixed with the net45 target of *SQLitePCLRaw.bundle_e_sqlite3*  so that it can be transitively applied? Or is having the bundle in the head project a requirement?
