### ISSUE TITLE
6.2.3 GetAll function is extremely slow.

### ISSUE THREAD

**Issue by EmilAlipiev** [reactiveui/Akavache#451]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**

GetAll function is super slow on version 6.2.3

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

If you have many objects with same type, i tested with 150 objects, GetAll function returns more than 10 secs. however using 6.0.31, result is returned 2-3 secs. I havent tested versions between yet but last good known version for me is 6.0.31. Versions before worked perfectly fine also.
There must be some major change in between.

**What is the expected behavior?**

that it returns faster
 

**Which versions of Akavache, and which platform / OS are affected by this issue? Did this work in previous versions of Akavache? Please also test with the latest stable and snapshot (https://www.myget.org/feed/Akavache/package/nuget/Akavache) versions.**

I tested on Android emulator and real device.
Emulator with version 8.1 and 9, Device with 6.0.1

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by glennawatson** [comment]
Can you provide a minimal demo to make it easy to diagnose?

**Comment by PureWeen** [comment]
@EmilAlipiev  are you still seeing this issue? Can you paste here what the type looks like that you are saving?

**Comment by EmilAlipiev** [comment]
Sorry for not being able to answer here long time. i will take action here in next days by providing text case or debug the source code myself but yes, i still see this problem in the most latest version. thats why i was stick with 6.0.31 version long time.
