### ISSUE TITLE
Bulk operations take a lot of time

### ISSUE THREAD

**Issue by crehmann** [reactiveui/Akavache#470]
I am using the latest version of Akavache (6.4.1) and I experience that a bulk insertion of around 3000 objects takes quite some time (2min). 

So I started to look into the code of Akavache and discovered the BulkOperationsMixin where the bulk insertion is implemented with an extension method. This extension method checks if the used blob cache implements the IObjectBulkBlobCache interface. 
However, I do not find any implementation of this interface within the library. 

Do I miss something or is my assumption correct, that the insertion is not performed in one bulk?

**Comment by PureWeen** [comment]
That assessment seems correct. The interface was added some time ago
https://github.com/reactiveui/Akavache/commit/b5b4a637c03a7d7669e93c30bce2b0b5ce9e5404

But it hasn't really been realized anywhere it seems

Can you attach a sample of what you're doing so once this is looked at it can be tested against your scenario?

**Comment by EmilAlipiev** [comment]
i wonder if that is related to this issue. https://github.com/reactiveui/Akavache/issues/451
I am still using 6.0.31 version because of the issue. do you see better performance using 6.0.31?

**Comment by lywyn** [comment]
Xamarin Android project inserting 15,000 barcodes on startup.  We upgraded solution from Akavache 5 to 6.5.1 and noticed massive slow down, it took 327 seconds. Downgraded to 6.0.31 after seeing @EmilAlipiev's comment and re-run test load and only took 4 seconds which was around the same speed we had on version 5.

**Comment by drjaydenm** [comment]
We upgraded to Akavache 6.5.9 from version 5.0.0 and noticed a massive slowdown in bulk operations, matching the description of the previous posts on this issue. Downgrading to 6.0.31 definitely resolved the issue for us too - so this issue still exists in the latest 6.5.9 release

**Comment by wadepowell** [comment]
We are seeing the same significant performance slowdown in our Xamarin Forms iOS project after upgrading to any version > 6.0.31.

Downgrading back to 6.0.31 resolved the issue.

**Comment by lywyn** [comment]
Just tried 6.8.1 doing a bulk load and Android prompted to wait or kill the app. Before upgrade the bulk load was under 5 seconds, after it was so long I ended up killing app. Reverted back to 6.0.31.  Also updated all the dependencies
