### ISSUE TITLE
Summer time lost when retrieving date

### ISSUE THREAD

**Issue by FruitAndAShape** [reactiveui/Akavache#492]
I've installed version 6.7.1 and I'm still getting the bug mentioned here...

[https://github.com/reactiveui/Akavache/issues/458](https://github.com/reactiveui/Akavache/issues/458)

i.e. a time goes in the cache as 14:00 and comes out as 13:00.

Why doesn't the fix work?

**Comment by glennawatson** [comment]
You need to pick one, open or close :)

**Comment by glennawatson** [comment]
You can in the mean time use your own JsonSerializerSettings to override the functionality. It's overridable. I think the bug persists since we always import the time as UTC no matter what.

**Comment by FruitAndAShape** [comment]
> You need to pick one, open or close :)

Last in wins. :)

**Comment by FruitAndAShape** [comment]
> You can in the mean time use your own JsonSerializerSettings to override the functionality. It's overridable. I think the bug persists since we always import the time as UTC no matter what.

I'll give it a go. The post I linked to says...

> A custom JsonSerializerSettings.ContractResolver is now ignored.

**Comment by glennawatson** [comment]
https://github.com/reactiveui/Akavache/blob/e18024c39e774b21d513d5bfc5eaa7bb0150c445/src/Akavache.Core/Json/JsonDateTimeTickConverter.cs#L55

So by default now we are doing UTC time serialisation (which is not what the documentation says), so you can set the override for the ForcedDateTimeKind on the blob cache potentially to local.

**Comment by FruitAndAShape** [comment]
`JsonSerializerSettings.ContractResolver` works.

Plus... `BlobCache.Secure.ForcedDateTimeKind = DateTimeKind.Local;` appears to solve my issue.

Thanks.

**Comment by glennawatson** [comment]
I've made a task to update the documentation..

**Comment by glennawatson** [comment]
Documentation updated.
