### ISSUE TITLE
DateTime UTC lost

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/Akavache#500]
But dates, by default,  are returned in DateTimeKind.Utc: 

[JsonDateTimeTickConverter.cs#L55](https://github.com/reactiveui/Akavache/blob/e18024c39e774b21d513d5bfc5eaa7bb0150c445/src/Akavache.Core/Json/JsonDateTimeTickConverter.cs#L55)

Shouldn't these be converted to DateTimeKind.Local?

**Comment by anaisbetts** [comment]
Consider the following:

1. User is in LA, uses the app and saves a bunch of data
2. User gets on a plane, flies to Berlin, changes time zone on phone
3. User opens the app, all the times are Weirded because now half of them are stored in "Local" (Berlin) and half of them are stored in "Local" (LA)

**Comment by glennawatson** [comment]
This was a copy paste from a user btw. Set to investigate.

**Comment by glennawatson** [comment]
This relates to the following in our documentation:

> By default JSON.NET's BSON implementation writes DateTime as UTC and reads it back in local time. To override the reader's behavior you can set BlobCache.ForcedDateTimeKind as in the following example

I changed it so we serialize and return in UTC.
