### ISSUE TITLE
Xamarin Forms iOS build error - Native Linking failed

### ISSUE THREAD

**Issue by Morhpeuss** [reactiveui/Akavache#511]
**Describe the bug**
I get this error on build iOS project:
Native linking failed, undefined symbol: _sqlite3_rekey_v2. This symbol was referenced by the managed member SQLitePCL.SQLite3Provider_internal/NativeMethods.sqlite3_rekey_v2. Please verify that all the necessary frameworks have been referenced and native libraries linked.	

The build error is only for version 6.6.1 or higher with version 6.5.20 the build is done

**Steps To Reproduce**
Provide the steps to reproduce the behavior:
1. Add akavache 6.6.1 or higher
2. Build the xamarin iOS project
3. See error

**Expected behavior**
The build is done without errors

**Environment**

- OS:           WIN10
- VS:            2019.16.2.5
- Xamarin :  4.2.0815419

**Comment by glennawatson** [comment]
You'll probably want to open an issue over at 

https://github.com/ericsink/SQLitePCL.raw

Looks like Eric has a method he's not using which references the native library. 

I don't think this is directly related to akavache.
