### ISSUE TITLE
Using Akavache in a Net Core 3.0 Console Application on Linux

### ISSUE THREAD

**Issue by oliverw** [reactiveui/Akavache#517]
I realize this setup is not listed in the readme, but I'd still like to know if its possible to use Akavache in a Net Core 3.0 Console Application on Linux. Attempting to `dotnet build` such a project on Linux results in the following error:

> /usr/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(263,5): error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App' was not recognized

**Comment by glennawatson** [comment]
I think this would be solved with a splat 9 update. I won't realistically get to this until late this week at the earliest.

**Comment by oliverw** [comment]
@glennawatson Fair enough. Closing.

**Comment by jbachelor** [comment]
Hi @glennawatson - I just added Akavache 6.9.10 to a Xamarin.Forms app, which I am developing using Visual Studio 2019 for Mac. The app includes a unit test project, targeting .net core 3.0. The cross-platform project targets .net standard 2.0.

When I add the Akavache nuget package (to the cross-platform project, the Android project, and the iOS project), my unit test project no longer compiles, giving a very similar (or possibly the same) error @oliverw described on his Linux machine:

`/usr/local/share/dotnet/sdk/3.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(5,5): Error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App' was not recognized (NETSDK1073) (XamFormsSample.UnitTests)`

When I tested this on a Windows machine running Visual Studio 2019, everything seems to work fine. Additionally, if I target .net core 2.1 in the unit test project, it will compile on the Mac.

Would this be the same issue as reported above? I have attached a project that demonstrates the issue on a Mac:

[XamFormsSample-akavache.zip](https://github.com/reactiveui/Akavache/files/4006084/XamFormsSample-akavache.zip)

**Comment by vkormushkin** [comment]
Hi, I came across the same issue as @jbachelor did. My setup is pretty much the same:VS for mac, common netstandard 2.0 project and dotnet core 3.0 unit test project. Referencing akavache NuGet package to the netstandard project leads to the compilation error mentioned above.

**Comment by Planverlust** [comment]
Same here with Net Core 3.1 and Akavache 6.9.10

**Comment by glennawatson** [comment]
This was fixed in #555

**Comment by Px7-941** [comment]
Tested with Net Core 3.1 and Akavache V6.10.2 and it builds. Thx for the fix.

**Comment by jbachelor** [comment]
Just tested with .net core 3.1 and Akavache 6.10.2, and all is working great. Thanks so much for your hard work!

**Comment by Teknel** [comment]
I am testing in .Net Core 3.1 with VS2019.
Compile is OK.
But on InsertObject or GetObject i have this error:
System.Exception: 'Can't find a TaskPoolScheduler. You probably accidentally linked to the PCL Akavache in your app.'

I actualized all NuGet packages to 6.10.3.
The app works fine on .net 
What I am doing wrong?

**Comment by glennawatson** [comment]
We pushed an update yesterday that should fix your exception.
