### ISSUE TITLE
DateTime handling serializes in UTC but Deserializes in Local.

### ISSUE THREAD

**Issue by anaisbetts** [reactiveui/Akavache#53]
https://gist.github.com/niik/09047dd5bf035359be57 has the gory details. Basically, we save DateTimes as UTC, but restore them as Local times. That's Bad™.

**Comment by Qwin** [comment]
@paulcbetts This is also happening to me with akavache 4.1.2

**Comment by ghuntley** [comment]
@qwin can you please try with 5.x,  if still happening open a GitHub issue, fill in the template and supply a test case.

**Comment by Qwin** [comment]
@ghuntley will try

**Comment by poimis** [comment]
Yes, this is still broken in 5.0.0

**Comment by kjeremy** [comment]
I'm seeing this in 5.0.0.1477562522 on Android with `DateTimeOffset`.  Is there a workaround?

**Comment by andrius-k** [comment]
I'm seeing this in 5.0.0 as well

**Comment by kjeremy** [comment]
@andrius-k https://github.com/akavache/Akavache#datetimedatetimeoffset-considerations

**Comment by andrius-k** [comment]
@kjeremy missed that, thanks a lot ;)
