### ISSUE TITLE
Where to put Akavache.Registrations.Start("ApplicationName") in Xamarin.Forms?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [reactiveui/Akavache#531]
Hi, Wish you have a nice day!

I trying to install Akavache to Xamarin.Forms (I create app for Android, iOS and UWP).
Where I must put this code Akavache.Registrations.Start("ApplicationName") in App.cs of NetStandard project or in every platforms.

Thank you!

**Comment by kerbooo** [comment]
@nguyenthanhliemfc  Hello I achieve same issue installing package for **using Akavache.Sqlite3;** from nuget
