### ISSUE TITLE
 Dictionary storage List

### ISSUE THREAD

**Issue by XiaoBaiXJ** [reactiveui/Akavache#539]
Why does the value storage set in the dictionary fail? When reading, the value is zero

**Comment by XiaoBaiXJ** [comment]
![image](https://user-images.githubusercontent.com/44961186/70026616-3043eb00-15db-11ea-9b8d-9a2ca43d3392.png)

**Comment by XiaoBaiXJ** [comment]
Zero on read

**Comment by rdavisau** [comment]
You should either `await` (add `using System.Reactive.Linq`) or `.Subscribe()` your inserts.

**Comment by XiaoBaiXJ** [comment]
![image](https://user-images.githubusercontent.com/44961186/70053743-09081080-1611-11ea-8dd7-a1c0d9e829d5.png)
Can't you save the list directly?

**Comment by rdavisau** [comment]
Based on the error message, you might have something like 

`await cache.GetObject<CheckPlanSubmitted>(key);`

when you should have

`await cache.GetObject<List<CheckPlanSubmitted>>(key);`?

**Comment by XiaoBaiXJ** [comment]
Thanks,  It has been solved and adopted  await cache.GetObject<List<CheckPlanSubmitted>>(key);  Thanks
