### ISSUE TITLE
feature: Support for TvOS

### ISSUE THREAD

**Issue by jpiechowiak** [reactiveui/Akavache#540]
I would like to ask for a support for TvOS. SQLitePCLRaw is already supporting this platform, so I think it will be propably quite easy to add this one also for Akavache.
When I tried to use already in my project, then I received an error:

'Failed to initialize Akavache properly. Do you have a reference to Akavache.dll?'

I have similar implementation for other platforms and it is working fine.

**Comment by amirvenus** [comment]
Hi,

I am a contributor and I badly need this feature done!

Do I need to create a new Issue to suggest this feature so that I can add priority label or can it be added to this Issue?

Thanks!

**Comment by glennawatson** [comment]
All good. I closed the other issue since this one is open. I need to add netstandard2.1 support this weekend anyway so I will add the tvos support as well
