### ISSUE TITLE
[BUG] Akavache and Microsoft App Center - Xamarin Forms UWP store release will not build SQLitePCLRaw.core

### ISSUE THREAD

**Issue by JoshuaLogue** [reactiveui/Akavache#564]
**Describe the bug**
I am trying to create a Microsoft Store release for a Xamarin Forms app but it is failing to build 
when I have Compile with .NETNative tool chain enabled. It builds fine when this is not enabled and in Debug mode. I am using both Akavache and App Center so I assume it might be an issue with that? Or it could be a missing nuget package?

The error is:
error : Method 'SQLite3.GetErrmsg(sqlite3)' will always throw an exception due to the missing method 'raw.sqlite3_errmsg(sqlite3)' in assembly 'SQLitePCLRaw.core'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.

**Steps To Reproduce**
I am targeting NetStandard 2.0 and built for x86. Since I have App Center as well I have followed the advice in the read me and have this line when I initialise the app:
Akavache.Sqlite3.Registrations.Start("ApplicationName", () => SQLitePCL.Batteries_V2.Init());

Following packages in core project:
 `<PackageReference Include="akavache.core" Version="6.10.4" />
    <PackageReference Include="akavache.sqlite3" Version="6.10.4" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.0.2" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.0.2" />
    <PackageReference Include="SQLitePCLRaw.core" Version="2.0.2" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.0.2" />
    <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="2.0.2" />
 <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
<PackageReference Include="Microsoft.AppCenter" Version="2.6.4" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="2.6.4" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="2.6.4" />`

and in the UWP project
 `<PackageReference Include="akavache.core">
      <Version>6.10.4</Version>
    </PackageReference>
    <PackageReference Include="akavache.sqlite3">
      <Version>6.10.4</Version>
    </PackageReference> 
<PackageReference Include="Microsoft.AppCenter">
      <Version>2.6.4</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Analytics">
      <Version>2.6.4</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Crashes">
      <Version>2.6.4</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.2.9</Version>
    </PackageReference>
 <PackageReference Include="Newtonsoft.Json">
      <Version>12.0.3</Version>
    </PackageReference>
    <PackageReference Include="Splat">
      <Version>9.3.11</Version>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3">
      <Version>2.0.2</Version>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.bundle_green">
      <Version>2.0.2</Version>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.core">
      <Version>2.0.2</Version>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3">
      <Version>2.0.2</Version>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3.uwp10">
      <Version>1.1.14</Version>
    </PackageReference>`
**Expected behavior**
For the app to build and `run`
**Environment**

- OS:      Xamarin Forms UWP
- Device:   UWP
- Version:   Target version is v1809

**Comment by glennawatson** [comment]
Might be worth asking @ericsink on the sqliteRawPcl project.

**Comment by JoshuaLogue** [comment]
Yes I will try that.
I downgraded Akavache as per this issue: https://github.com/reactiveui/Akavache/issues/502
I'm now getting the error:
error APPX1101: Payload contains two or more files with the same destination path 'e_sqlite3.dll'. Source files:
error APPX1101: *\.nuget\packages\sqlitepclraw.lib.e_sqlite3\2.0.0\runtimes\win10-x86\nativeassets\uap10.0\e_sqlite3.dll
error APPX1101: C:\Users\josh\.nuget\packages\sqlitepclraw.lib.e_sqlite3.v140\1.1.13\runtimes\win10-x86\native\e_sqlite3.dll

**Comment by JoshuaLogue** [comment]
So I got this to build.

Step 1: remove all Akavache and SQLite packages from UWP project.
Step 2: as per this conversation to get around memory issues: https://github.com/dotnet/corert/issues/7687#issuecomment-520948887
I had to downgrade akavache to v6.5.1
