### ISSUE TITLE
[BUG] Data persistence

### ISSUE THREAD

**Issue by alex0916** [reactiveui/Akavache#571]
**Describe the bug**

I'm saving a token using BlobCache.Secure in xamarin forms and it works fine but when I close the app and re-enter the token is null.
I put the BlobCache.ApplicationName in App.xaml.cs below InitializeComponent method

**Expected behavior**

Get the token even if the app is restarted

**Environment**

- OS:        Android, iOS, UWP
- Version:    Akavache.core 6.10.4

**Additional context**

**Comment by anaisbetts** [comment]
You're either killing the app forcefully, or you're not calling `BlobCache.Shutdown`
