### ISSUE TITLE
[BUG] Cache reading fails in Xamarin.iOS

### ISSUE THREAD

**Issue by nologinatgit** [reactiveui/Akavache#589]
**Describe the bug**

In a cross-platform project we use Akavache as our cache. The target is .Net Standard 2.1, and we use version 6.10.20.

We simply use the following for writing:

`await cache.InsertObject(userIDKey, userID);`

For reading:
`await cache.GetObject<Guid>(userIDKey);`

It works on _Xamarin.Android_, for both reading and writing.

Unfortunately, we can _only write_ in **Xamarin.iOS** (the cache does contain the item).
When we try to read it, the following exception occurs:

> Operation is not supported on this platform.
> Stacktrace:   at System.Reflection.Emit.DynamicMethod..ctor (System.String name, System.Reflection.MethodAttributes attributes, System.Reflection.CallingConventions callingConvention, System.Type returnType, System.Type[] parameterTypes, System.Type owner, System.Boolean skipVisibility) [0x00006] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Reflection.Emit/DynamicMethod.notsupported.cs:74 \n  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ILEmitResolverBuilder.BuildTypeNoCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite) [0x00038] in <b024453eb6a0490d8a11f8d734a13c32>:0 \n  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ILEmitResolverBuilder.BuildType (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite) [0x00055] in <b024453eb6a0490d8a11f8d734a13c32>:0 \n  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ILEmitResolverBuilder.Build (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite) [0x00039] in <b024453eb6a0490d8a11f8d734a13c32>:0 \n  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CompiledServiceProviderEngine.RealizeService (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite) [0x00006] in <b024453eb6a0490d8a11f8d734a13c32>:0 \n  at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>n__0 (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite) [0x00000] in <b024453eb6a0490d8a11f8d734a13c32>:0 \n  at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine+<>c__DisplayClass1_0.<RealizeService>b__1 () [0x00000] in <b024453eb6a0490d8a11f8d734a13c32>:0 \n  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:534 \n  at System.Threading.Tasks.Task.Execute () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 \n"

**Steps To Reproduce**

1. Save an item to the cache
2. Try to read it
3. See error

**Expected behavior**

We expect the item to be read from the cache without a problem.

**Screenshots**

**Environment**

- OS:       iOS 13.5
- Device:   Simulator 11.5
- Xamarin: 16.6.000.1062 (d16-6@41e1f0e)
- Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
**Additional context**

**Comment by glennawatson** [comment]
Got a sample, I've got a couple different projects where iOS/Android intermingle.

**Comment by nologinatgit** [comment]
> Got a sample? I've got a couple different projects where iOS/Android intermingle.

What do you mean by intermingle? Causing problems by not finding the proper cache object?
I don't have a simple test project yet but it is quite strange that writing works and the same object causes that exception. We use MvvmCross as the dependency injection container and handler, and the cache object is presented via constructor injection. As the writing works, I think that the dependency injection works good. 
Could be some JSON.NET problem?

We use it with the following configuration:

    Splat.Locator.CurrentMutable.Register(
                () => new JsonSerializerSettings()
                {
                  // these are the defaults configured for Splat in Akavache - I can't why we can't keep them
                  ObjectCreationHandling = ObjectCreationHandling.Replace,
                  ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                  TypeNameHandling = TypeNameHandling.All
                },
                typeof(JsonSerializerSettings));

**Comment by glennawatson** [comment]
I just mean I've used Android iOS for other large projects so a sample would be great to help isolate it for you

**Comment by glennawatson** [comment]
As answered on your StackOverflow question:

> It is not a Akavache failure, the DependencyInjection/ServiceLookup you are using is trying to emit IL and that is not allowed by iOS (DynamicMethod.notsupported), i.e. Microsoft.Extensions.DependencyInjection is not iOS safe, there is a "preview" version of that library available, but I'm not sure if that does anything to help on iOS, you can always open an issue @ https://github.com/dotnet/extensions
