### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'e_sqlite3' or one of its dependencies

### ISSUE THREAD

**Issue by Schtailian** [reactiveui/Akavache#754]
**Describe the bug**
When i updated from 7.3.1 to 8.1.1 i got this error as described also here #442. No solution provided in similar issues would solve my issue .

![image](https://user-images.githubusercontent.com/10855460/148927236-311df842-2864-4080-b12d-af5ea7943c36.png)

The dlls in the output folder
![image](https://user-images.githubusercontent.com/10855460/148942707-bd1caa24-b927-4041-a3ba-6cf83bb51f69.png)

I did only update akavache, all other packages stayed the same and I was also using .Net6 with the previous versions. 
When i downgrade to 7.3.1 everything works as expected also without SQLitePCLRaw.bundle_e_sqlite3

**Expected behavior**
The package should be found and loaded.

**Environment**
- OS:  Windows 10
- Device:   PC
- Net: 6.0
- Version:   8.1.1
- Working Version: 7.3.1

**Comment by EmilAlipiev** [comment]
are you using appcenter package? usually it is problem between those 2 
Also why do you need e_sqlite3 package for?  this might cause as well

**Comment by Schtailian** [comment]
I tried the e_sqlite3 only, because that what was suggested in #442 

Anyway, i tried it again, still version 8.1.1, and now it works. I had only minor updates on other packages... Don't know what was wrong. Closing it

**Comment by glennawatson** [comment]
There's been some issues with visual studio lately with sqlite so could be that
