### ISSUE TITLE
[BUG] Propably serialization bug on retrieval GetOrFetchObject.

### ISSUE THREAD

**Issue by tomasfil** [reactiveui/Akavache#764]
**Describe the bug**

The cache gets corrupted somehow, and returned object properties have default values, or nulls.

I did reproduction repo Akavache_InMemoryCacheTests: 
https://github.com/tomasfil/ReactiveUI_Tests

Run the project and sooner or later you will start getting null reference exception. Doesnt matter if it is InMemory or LocalCache, or any other cache.

**Steps To Reproduce**

Run the included project.

**Expected behavior**

Should return valid serialized objects

**Comment by tomasfil** [comment]
After some testing the issue is ReactiveObject, upon removing inheritation from ReactiveObject, then the cache is running just fine.

**Comment by glennawatson** [comment]
ReactiveObject has some quirks in regards to serialisation.

**Comment by tomasfil** [comment]
Almost all my domain object are inheriting ReactiveObject, so forth making it every single one not usable with the Akavache cache...

**Comment by tomasfil** [comment]
@glennawatson Any tip how to make this work? It seems like I would need to implement whole new layer for DTOs, that would get cached.
That would be Entity -> DTO -> Domain object

Which doesnt really makes sense, because all of the apps are WPF, accessing database directly via repository pattern on top of Entity framework, so the Entities are our DTOs.

Implementing DTOs would require to make huge infrastructure changes, since some entities are desired and some not to be cached.

The most reasonable thing is to cache normally ReactiveObject, but I am not sure where the issue lies in the first place.

**Comment by glennawatson** [comment]
If it was me I would use source generators to generate the dto at compile time so I'm not having to manually generate them all. 

There are some serialisation hints in the docs that may help

One thing I can think of causing issues is Akavache uses the binary compiler by default.

**Comment by glennawatson** [comment]
https://www.reactiveui.net/docs/handbook/data-persistence/

**Comment by tomasfil** [comment]
I am aware of DTO generators, but for this project it doesnt make sense to map the entity 2 times, it is just excesive.

Binary compiler? Is there way for me to test out this theory? I went through source code briefly, but didnt find out what you mean

**Comment by tomasfil** [comment]
To complement, the issue is there not only on NET 5, but on NET 6 and all latest versions:
![image](https://user-images.githubusercontent.com/34779382/154701670-173ddce6-08aa-4ffb-920e-c55e45eecb27.png)

**Comment by tomasfil** [comment]
Oof, so, it seems like restarting the computer fixed the issue 😄 I will test out tomorrow and close the issue if that is the case
