### ISSUE TITLE
[BUG] Localmachine data is lost on every Android version increment or change

### ISSUE THREAD

**Issue by Vuyiswamb** [reactiveui/Akavache#808]
Good Day all 

 am using BlobCache(Akavache.Core)  to store the token 

https://www.nuget.org/packages/akavache.core/

```

    public static async Task Store_Token(TOKEN_MODEL Token)
        {
            try
            {
               await BlobCache.LocalMachine.InsertObject("TOKEN", Token);
            }
            catch (KeyNotFoundException ex)
            {
                throw ex;
            }
        }

```
and retrieve it like this 

```
       public async static Task<TOKEN_MODEL> Retrieve_Token()
        {
            TOKEN_MODEL Userinfo = new TOKEN_MODEL();
            try
            {
                try
                {
                    Userinfo = await BlobCache.LocalMachine.GetObject<TOKEN_MODEL>("TOKEN");
                }
                catch (KeyNotFoundException)
                {
                }
            }
            catch (Exception)
            {
            }
            return Userinfo;
        }
```

 i realized that every time i do a release this token is lost.  so when a user do an update on the app this token is lost. so i tested this by changing the version of the android project. if i leave it , it keeps the token but if change it it wipes also the token 

Thanks

**Comment by anaisbetts** [comment]
LocalMachine is not guaranteed to be preserved on Android, use UserAccount instead

**Comment by Vuyiswamb** [comment]
Thank you for the response anaisbetts , is Secure also a good option ?

**Comment by Vuyiswamb** [comment]
Thank you very much .
